[package]
name = "rust-em-100-dias"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[workspaces]]
members = [
    "Dia 01",
    "Dia 02",
]

[dependencies]
